# Frontend Development category — tiered classifier vocabulary
#
# Core keywords are strong standalone evidence; supporting keywords require
# aggregation. NOISE_KEYWORDS are excluded from scoring entirely.

# Positive evidence: Frontend Development / UI Implementation / Web UI.
POSITIVE_KEYWORDS = {

    "frameworks": {
        "core": {
            "react": 9,
            "reactjs": 9,
            "react.js": 9,
            "nextjs": 9,
            "next.js": 9,
            "vue": 9,
            "vuejs": 9,
            "vue.js": 9,
            "angular": 9,
            "angularjs": 9,
            "svelte": 9,
            "sveltejs": 9,
            "solidjs": 8,
            "preact": 8,
            "qwik": 8,
        },
        "supporting": {
            "redux": 4,
            "zustand": 4,
            "pinia": 4,
            "vuex": 4,
            "ngrx": 4,
            "recoil": 4,
            "jotai": 4,
        },
    },

    "styling": {
        "core": {
            "tailwind": 8,
            "tailwindcss": 8,
            "bootstrap": 7,
            "material ui": 8,
            "mui": 7,
            "chakra ui": 7,
            "shadcn": 8,
            "shadcn ui": 8,
            "ant design": 7,
            "antd": 7,
            "styled components": 7,
            "emotion": 6,
            "sass": 7,
            "scss": 7,
            "css modules": 7,
            "gsap": 6,
        },
        "supporting": {
            "less": 3,
            "responsive design": 4,
            "responsive web": 4,
            "mobile first": 3,
            "grid layout": 3,
            "flexbox": 3,
            "css grid": 3,
            "animation": 2,
            "transitions": 2,
        },
    },

    "ui_ux": {
        "core": {
            "frontend": 8,
            "front-end": 8,
            "front end": 8,
            "ui development": 8,
            "ui implementation": 8,
            "figma to code": 9,
            "figma to html": 9,
            "figma to react": 9,
            "figma to vue": 9,
            "figma to angular": 9,
            "figma to next": 9,
            "figma to svelte": 9,
            "figma to tailwind": 9,
            "figma to component": 9,
            "figma to page": 9,
            "figma to ui": 9,
            "figma to web": 9,
            "figma to app": 9,
            "figma to dashboard": 9,
            "figma to landing": 9,
            "figma to website": 9,
            "figma to prototype": 9,
            "figma to mockup": 9,
            "figma to design": 9,
            "figma to pixel": 9,
            "figma to screen": 9,
            "figma to view": 9,
            "figma to layout": 9,
            "figma to interface": 9,
            "figma to element": 9,
            "figma to section": 9,
            "figma to block": 9,
            "figma to widget": 9,
            "figma to card": 9,
            "figma to form": 9,
            "figma to table": 9,
            "figma to modal": 9,
            "figma to popup": 9,
            "figma to menu": 9,
            "figma to sidebar": 9,
            "figma to header": 9,
            "figma to footer": 9,
            "figma to nav": 9,
            "figma to navbar": 9,
            "pixel perfect": 8,
            "pixel-perfect": 8,
            "pixel by pixel": 8,
            "design to code": 8,
            "mockup to code": 8,
            "design implementation": 8,
            "ui from figma": 8,
            "ui from design": 8,
            "ui from mockup": 8,
            "ui from prototype": 8,
        },
        "supporting": {
            "exact match": 3,
            "ui": 3,
            "ux": 3,
            "user interface": 3,
            "user experience": 3,
            "design system": 4,
            "component library": 4,
            "storybook": 4,
        },
    },

    "web_platforms": {
        "core": {
            "wordpress": 8,
            "woocommerce": 7,
            "shopify": 7,
            "webflow": 8,
            "wix": 7,
            "squarespace": 6,
            "elementor": 7,
            "divi": 6,
            "framer": 7,
            "duda": 7,
            "ثيم سلة": 6,
            "ثيمات سلة": 6,
            "ووردبريس": 7,
            "الووردبريس": 7,
            "وورد بريس": 7,
            "وردبيرس": 7,
            "ووردبيرس": 7,
            "وورد بيرس": 7,
            "وردبريس": 7,
            "ورد بريس": 7,
            "شوبيفاي": 7,
            "ووكومرس": 7,
            "e-commerce website": 7,
            "e-commerce site": 7,
            "e-commerce store": 7,
            "ecommerce website": 7,
            "ecommerce site": 7,
            "ecommerce store": 7,
            "multi vendor": 6,
            "متعددة التجار": 6,
            "متعدد التجار": 6,
            "موقع إلكتروني": 6,
            "مواقع إلكترونية": 6,
            "تصميم موقع": 6,
            "تطوير مواقع": 6,
            "تصميم مواقع": 6,
            "مطور مواقع": 6,
            "web developer": 7,
            "web development": 7,
            "web designer": 6,
            "web design": 6,
            "website development": 7,
            "website design": 6,
            "website build": 6,
            "landing page": 6,
            "web app": 6,
            "webapp": 6,
        },
        "supporting": {
            # Store mention alone is not web-dev evidence (customer service,
            # store management, product-entry gigs all name their store).
            "متجر إلكتروني": 4,
            # Salla platform names demoted core->supporting: marketing/
            # management/CRO hybrids (إدارة متجر سلة, تحسين معدل التحويل)
            # were direct-selecting on the platform name alone.
            "منصة سلة": 4,
            "متجر سلة": 4,
            "e-commerce": 4,
            "ecommerce": 4,
            "theme": 3,
            "plugin": 3,
            "template": 3,
            "custom theme": 4,
            "custom plugin": 4,
        },
    },

    "languages": {
        "core": {
            "html": 7,
            "css": 7,
            "javascript": 7,
            "typescript": 7,
        },
        "supporting": {
            "jsx": 3,
            "tsx": 3,
            "es6": 3,
            "es2015": 3,
            "web components": 3,
            "shadow dom": 3,
        },
    },

    # QA-tool names are deliberately absent from core: in production they
    # mark scraping/automation gigs, not frontend builds.
    "testing": {
        "core": {},
        "supporting": {
            "jest": 3,
            "unit test": 3,
            "integration test": 3,
            "e2e": 3,
            "end to end": 3,
            "testing library": 3,
        },
    },
}


# Negative evidence: other software domains to avoid overlap.
NEGATIVE_KEYWORDS = {

    "backend": {
        "core": {
            "laravel": 8,
            "django": 7,
            "flask": 6,
            "fastapi": 6,
            "spring boot": 8,
            "spring": 7,
            ".net": 7,
            "asp.net": 7,
            "nodejs": 7,
            "node.js": 7,
            "express": 6,
            "nestjs": 7,
            "ruby on rails": 7,
            "ruby": 5,
            "golang": 4,
            "rust": 4,
            "rest api": 6,
            "restful": 6,
            "graphql": 5,
            "grpc": 5,
            "microservice": 6,
            "microservices": 6,
            "api development": 6,
            "api integration": 5,
            "backend": 7,
            "back-end": 7,
            "server side": 6,
        },
        "supporting": {
            "postgresql": 3,
            "mysql": 3,
            "mongodb": 3,
            "redis": 3,
            "elasticsearch": 3,
            "authentication": 2,
            "authorization": 2,
            "oauth": 2,
            "jwt": 2,
            "database design": 3,
            "database schema": 3,
        },
    },

    "mobile": {
        "core": {
            "flutter": 8,
            "dart": 7,
            "react native": 8,
            "swift": 7,
            "swiftui": 7,
            "uikit": 7,
            "kotlin": 7,
            "jetpack compose": 7,
            "android": 6,
            "android studio": 7,
            "ios": 6,
            "iphone": 6,
            "ipad": 6,
            "xcode": 7,
            "mobile app": 7,
            "mobile application": 7,
            "app store": 5,
            "google play": 5,
        },
        "supporting": {
            "cross-platform": 3,
            "cross platform": 3,
            "ionic": 4,
            "capacitor": 4,
            "cordova": 4,
            "firebase": 3,
            "supabase": 3,
        },
    },

    "game": {
        "core": {
            "unity": 8,
            "unity3d": 8,
            "unreal engine": 8,
            "unreal": 7,
            "ue5": 8,
            "ue4": 8,
            "godot": 8,
            "game design": 8,
            "game development": 8,
            "game dev": 7,
            "gameplay": 7,
            "game mechanic": 7,
            "game mechanics": 7,
            "game programmer": 7,
            "game developer": 7,
            "indie game": 7,
            "mobile game": 7,
            "pc game": 6,
            "console game": 6,
            "game prototype": 7,
            "تصميم لعبة": 7,
            "برمجة ألعاب": 7,
            "تطوير ألعاب": 7,
            "مطور ألعاب": 7,
        },
        "supporting": {
            "game level": 3,
            "level design": 3,
            "game world": 3,
            "game ai": 3,
            "npc": 2,
            "inventory system": 2,
            "quest system": 3,
            "dialogue system": 3,
            "game physics": 3,
            "collision detection": 3,
            "game state": 2,
            "game save": 2,
            "save system": 2,
            "game balance": 3,
            "game economy": 3,
            "microtransaction": 2,
            "in-app purchase": 2,
            "game monetization": 3,
        },
    },

    "enterprise": {
        "core": {
            "erp": 7,
            "crm": 7,
            "wms": 7,
            "saas": 6,
            "netsuite": 7,
            "netsuite": 7,
            "business central": 7,
            "dynamics 365": 7,
        },
        "supporting": {
            "mvp": 3,
            "software development": 4,
            "admin panel": 4,
            "control panel": 3,
            "admin dashboard": 4,
            "user management": 4,
            "inventory management": 4,
        },
    },

    "data_analysis": {
        "core": {
            "data analysis": 8,
            "data analyst": 8,
            "power bi": 8,
            "tableau": 8,
            "business intelligence": 7,
            "business analyst": 7,
            "financial analysis": 8,
            "financial analyst": 8,
            "looker": 7,
            "looker studio": 7,
            "qlik": 7,
            "تحليل بيانات": 8,
            "محلل بيانات": 8,
            "تحليل مالي": 8,
        },
        "supporting": {
            "excel": 4,
            "pivot table": 4,
            "dashboard": 3,
            "analytics": 2,
            "kpi": 3,
            "reporting": 2,
            "etl": 3,
        },
    },

    "ai_ml": {
        "core": {
            "machine learning": 8,
            "deep learning": 8,
            "neural network": 7,
            "tensorflow": 8,
            "keras": 7,
            "pytorch": 8,
            "scikit-learn": 8,
            "sklearn": 8,
            "nlp": 7,
            "natural language processing": 7,
            "computer vision": 7,
            "llm": 7,
            "large language model": 7,
            "openai": 7,
            "gpt": 6,
            "data science": 8,
            "data scientist": 8,
            "predictive model": 7,
            "forecasting model": 7,
            "recommendation system": 7,
            "recommendation engine": 7,
        },
        "supporting": {
            "chatgpt": 3,
            "transformer": 3,
            "regression": 3,
            "classification": 3,
            "clustering": 3,
            "random forest": 4,
            "xgboost": 4,
            "lightgbm": 4,
            "hugging face": 4,
            "langchain": 4,
            "rag": 3,
            "fine-tuning": 4,
            "fine tuning": 4,
            "model training": 4,
        },
    },

    "education": {
        "core": {
            "teach": 7,
            "teaching": 7,
            "teacher": 7,
            "tutor": 7,
            "tutoring": 7,
            "مدرب": 6,
            "تعليم": 6,
            "تعليمي": 6,
            "معلم": 6,
            "مدرس": 6,
        },
        "supporting": {
            "mentor": 3,
            "mentoring": 3,
            "training": 3,
            "course": 3,
            "courses": 3,
            "curriculum": 3,
            "lesson": 2,
            "lessons": 2,
            "student": 2,
            "students": 2,
        },
    },
}


# Hard rejects: unrelated work rejected when no positive signal exists.
HARD_REJECT_KEYWORDS = {
    # Data-entry gigs reach frontend only via incidental html/format vocab.
    "data entry",
    "graphic design",
    "photoshop",
    "illustrator",
    "video editing",
    "motion graphics",
    "translation",
    "digital marketing",
    "google ads",
    "facebook ads",
    "backlink",
    "backlinks",
    "link building",
    "copywriting",
    "lead generation",
    "lead gen",
    "generación de leads",
    "commission only",
    "عمولة فقط",
    "internship",
    "intern",
    "volunteer",
    "unpaid",
    "تدريب صيفي",
    "متدرب",
    "متطوع",
    "بدون مقابل",
    "lead generating", "lead generators", "lead generator", "جلب العملاء", "letter writing", "request letter",
}


# Noise: intentionally unscored terms that are too ambiguous to classify.
NOISE_KEYWORDS = {
    "system", "systems",
    "platform", "platforms",
    "api",
    "app", "apps", "application", "applications",
    "user", "users",
    "login", "signup", "session",
    "roles", "permissions",
    "نظام", "أنواع",
    "منصة", "منصات",
    "برنامج", "برامج", "برمجية",
    "موقع", "مواقع",
    "متجر", "متاجر",
    "واجهة", "تكامل", "التوثيق",
    "جوال", "موبايل",
    "المستخدمين",
    "صلاحيات",
}


# Runtime invariant: noise terms must never enter scored vocabulary.
def _all_scored_keywords():
    for polarity in (POSITIVE_KEYWORDS, NEGATIVE_KEYWORDS):
        for category in polarity.values():
            for tier in ("core", "supporting"):
                for kw in category.get(tier, {}):
                    yield kw


_collision = NOISE_KEYWORDS.intersection(_all_scored_keywords())
if _collision:
    raise AssertionError(
        "The following NOISE_KEYWORDS were found inside a scored "
        "(core/supporting) dict — this reintroduces the false-positive/"
        "false-negative bug the tiered model was designed to prevent: "
        f"{sorted(_collision)}"
    )
