# Backend Development category — tiered classifier vocabulary
#
# Core keywords are strong standalone evidence; supporting keywords require
# aggregation. NOISE_KEYWORDS are excluded from scoring entirely.

# Positive evidence: Backend Development / APIs / Databases / Server-side.
POSITIVE_KEYWORDS = {

    "frameworks": {
        "core": {
            "laravel": 9,
            "php": 7,
            "django": 8,
            "flask": 7,
            "fastapi": 8,
            "spring boot": 9,
            "spring": 8,
            "asp.net": 8,
            "nodejs": 8,
            "node.js": 8,
            "nestjs": 8,
            "ruby on rails": 8,
            "ruby": 6,
            "golang": 6,
            "rust": 6,
            "java": 6,
        },
        "supporting": {
            "express": 3,
            "go": 3,
            "c#": 3,
            ".net": 4,
            "python": 3,
            "microservice": 4,
            "microservices": 4,
            "serverless": 4,
            "lambda": 4,
            "cloud function": 4,
        },
    },

    "databases": {
        "core": {
            "postgresql": 8,
            "postgres": 8,
            "mysql": 8,
            "mongodb": 8,
            "redis": 7,
            "elasticsearch": 7,
            "sqlite": 6,
            "oracle": 7,
            "sql server": 7,
            "dynamodb": 7,
            "cassandra": 7,
            "neo4j": 7,
            "firebase": 6,
            "supabase": 6,
        },
        "supporting": {
            "database design": 4,
            "database schema": 4,
            "migration": 3,
            "seed": 3,
            "orm": 3,
            "prisma": 4,
            "sequelize": 4,
            "typeorm": 4,
            "sqlalchemy": 4,
            "mongoose": 4,
        },
    },

    "api": {
        "core": {
            "rest api": 9,
            "restful": 8,
            "restful api": 9,
            "graphql": 8,
            "grpc": 7,
            "api development": 8,
            "api design": 8,
            "api integration": 7,
            "web api": 7,
            "web service": 7,
            "microservice": 7,
            "microservices": 7,
            "soap": 6,
            "websocket": 7,
            "socket.io": 7,
            "بناء api": 8,
        },
        "supporting": {
            "endpoint": 3,
            "endpoints": 3,
            "route": 2,
            "routes": 2,
            "controller": 3,
            "middleware": 3,
            "swagger": 4,
            "openapi": 4,
            "postman": 3,
        },
    },

    "architecture": {
        "core": {
            "backend": 8,
            "back-end": 8,
            "server side": 7,
            "server-side": 7,
            "serverless": 7,
            "hexagonal architecture": 7,
            "domain driven design": 7,
            "ddd": 6,
            "cqrs": 7,
            "event sourcing": 7,
            "message queue": 6,
            "rabbitmq": 7,
            "kafka": 7,
            "redis queue": 6,
        },
        "supporting": {
            "clean architecture": 3,
            "repository pattern": 4,
            "service layer": 4,
            "dependency injection": 4,
            "inversion of control": 4,
        },
    },

    "auth_security": {
        "core": {
            "authentication": 7,
            "authorization": 7,
            "oauth": 7,
            "oauth2": 7,
            "jwt": 7,
            "session management": 6,
            "rbac": 7,
            "role-based access": 7,
            "access control": 6,
            "encryption": 5,
            "hashing": 4,
            "bcrypt": 5,
        },
        "supporting": {
            "ssl": 3,
            "tls": 3,
            "login": 3,
            "signup": 3,
            "registration": 3,
            "password reset": 3,
            "two factor": 3,
            "2fa": 3,
            "mfa": 3,
        },
    },

    "devops_backend": {
        "core": {
            "docker": 7,
            "kubernetes": 7,
            "nginx": 6,
            "apache": 6,
            "linux server": 6,
            "ci/cd": 6,
            "jenkins": 6,
            "github actions": 6,
            "gitlab ci": 6,
            "heroku": 5,
            "digitalocean": 5,
            "linode": 5,
            "vultr": 5,
        },
        "supporting": {
            "aws": 3,
            "gcp": 3,
            "azure": 3,
            "deployment": 3,
            "scaling": 3,
            "load balancer": 3,
            "reverse proxy": 3,
            "cors": 3,
            "rate limiting": 3,
            "caching": 3,
            "cdn": 3,
        },
    },
}


# Negative evidence: other software domains to avoid overlap.
NEGATIVE_KEYWORDS = {

    # Recruitment/staffing ads are employment offers, not project gigs.
    "recruitment": {
        "core": {
            "staff augmentation": 8,
        },
        "supporting": {},
    },

    "writing_content": {
        "core": {
            "copywriter": 14,
        },
        "supporting": {},
    },

    "nocode_platforms": {
        "core": {
            "power apps": 8,
            "power platform": 8,
        },
        "supporting": {},
    },

    "frontend": {
        "core": {
            "react": 8,
            "reactjs": 8,
            "react.js": 8,
            "nextjs": 8,
            "next.js": 8,
            "vue": 8,
            "vuejs": 8,
            "vue.js": 8,
            "angular": 8,
            "angularjs": 8,
            "svelte": 8,
            "sveltejs": 8,
            "html": 6,
            "css": 6,
            "scss": 6,
            "sass": 6,
            "tailwind": 6,
            "tailwindcss": 6,
            "bootstrap": 6,
            "material ui": 6,
            "chakra ui": 6,
            "frontend": 7,
            "front-end": 7,
            "front end": 7,
            "landing page": 8,
            "landing pages": 8,
            "portfolio website": 7,
            "personal website": 7,
            "responsive design": 6,
            "responsive web": 6,
            "figma to code": 7,
            "figma to html": 7,
            "figma to react": 7,
            "wordpress": 8,
            "woocommerce": 8,
            "shopify": 8,
            "webflow": 7,
            "wix": 7,
            "elementor": 7,
            "divi": 7,
        },
        "supporting": {
            "javascript": 3,
            "typescript": 3,
            "ui implementation": 4,
            "pixel perfect": 4,
            "browser": 2,
            "web app": 4,
            "web application": 4,
        },
    },

    "mobile": {
        "core": {
            "flutter": 8,
            "dart": 7,
            "react native": 8,
            "swift": 7,
            "swiftui": 7,
            "uikit": 7,
            "kotlin": 7,
            "jetpack compose": 7,
            "android": 6,
            "android studio": 7,
            "ios": 6,
            "iphone": 6,
            "ipad": 6,
            "xcode": 7,
            "mobile app": 7,
            "mobile application": 7,
            "app store": 5,
            "google play": 5,
        },
        "supporting": {
            "cross-platform": 3,
            "cross platform": 3,
            "ionic": 4,
            "capacitor": 4,
            "cordova": 4,
            "firebase": 3,
            "supabase": 3,
        },
    },

    "game": {
        "core": {
            "unity": 8,
            "unity3d": 8,
            "unreal engine": 8,
            "unreal": 7,
            "ue5": 8,
            "ue4": 8,
            "godot": 8,
            "game design": 8,
            "game development": 8,
            "game dev": 7,
            "gameplay": 7,
            "game mechanic": 7,
            "game mechanics": 7,
            "game programmer": 7,
            "game developer": 7,
            "indie game": 7,
            "mobile game": 7,
            "pc game": 6,
            "console game": 6,
            "game prototype": 7,
            "تصميم لعبة": 7,
            "برمجة ألعاب": 7,
            "تطوير ألعاب": 7,
            "مطور ألعاب": 7,
        },
        "supporting": {
            "game level": 3,
            "level design": 3,
            "game world": 3,
            "game ai": 3,
            "npc": 2,
            "inventory system": 2,
            "quest system": 3,
            "dialogue system": 3,
            "game physics": 3,
            "collision detection": 3,
            "game state": 2,
            "game save": 2,
            "save system": 2,
            "game balance": 3,
            "game economy": 3,
            "microtransaction": 2,
            "in-app purchase": 2,
            "game monetization": 3,
        },
    },

    "enterprise": {
        "core": {
            "erp": 7,
            "crm": 7,
            "wms": 7,
            "saas": 6,
            "netsuite": 7,
            "netsuite": 7,
            "business central": 7,
            "dynamics 365": 7,
        },
        "supporting": {
            "mvp": 3,
            "software development": 4,
            "admin panel": 4,
            "control panel": 3,
            "admin dashboard": 4,
            "user management": 4,
            "inventory management": 4,
        },
    },

    "data_analysis": {
        "core": {
            "data analysis": 8,
            "data analyst": 8,
            "power bi": 8,
            "tableau": 8,
            "business intelligence": 7,
            "business analyst": 7,
            "financial analysis": 8,
            "financial analyst": 8,
            "looker": 7,
            "looker studio": 7,
            "qlik": 7,
            "تحليل بيانات": 8,
            "محلل بيانات": 8,
            "تحليل مالي": 8,
        },
        "supporting": {
            "excel": 4,
            "pivot table": 4,
            "dashboard": 3,
            "analytics": 2,
            "kpi": 3,
            "reporting": 2,
            "etl": 3,
        },
    },

    "ai_ml": {
        "core": {
            "machine learning": 8,
            "deep learning": 8,
            "neural network": 7,
            "tensorflow": 8,
            "keras": 7,
            "pytorch": 8,
            "scikit-learn": 8,
            "sklearn": 8,
            "nlp": 7,
            "natural language processing": 7,
            "computer vision": 7,
            "llm": 7,
            "large language model": 7,
            "openai": 7,
            "gpt": 6,
            "data science": 8,
            "data scientist": 8,
            "predictive model": 7,
            "forecasting model": 7,
            "recommendation system": 7,
            "recommendation engine": 7,
        },
        "supporting": {
            "chatgpt": 3,
            "transformer": 3,
            "regression": 3,
            "classification": 3,
            "clustering": 3,
            "random forest": 4,
            "xgboost": 4,
            "lightgbm": 4,
            "hugging face": 4,
            "langchain": 4,
            "rag": 3,
            "fine-tuning": 4,
            "fine tuning": 4,
            "model training": 4,
        },
    },

    "education": {
        "core": {
            "teach": 7,
            "teaching": 7,
            "teacher": 7,
            "tutor": 7,
            "tutoring": 7,
            "مدرب": 6,
            "تعليم": 6,
            "تعليمي": 6,
            "معلم": 6,
            "مدرس": 6,
        },
        "supporting": {
            "mentor": 3,
            "mentoring": 3,
            "training": 3,
            "course": 3,
            "courses": 3,
            "curriculum": 3,
            "lesson": 2,
            "lessons": 2,
            "student": 2,
            "students": 2,
        },
    },
}


# Hard rejects: unrelated work rejected when no positive signal exists.
HARD_REJECT_KEYWORDS = {
    # Data-entry gigs reach backend only via incidental db/tool vocabulary.
    "data entry",
    "إدخال بيانات",
    "graphic design",
    "photoshop",
    "illustrator",
    "video editing",
    "motion graphics",
    "translation",
    "digital marketing",
    "google ads",
    "facebook ads",
    "backlink",
    "backlinks",
    "link building",
    "copywriting",
    "lead generation",
    "lead gen",
    "generación de leads",
    "commission only",
    "عمولة فقط",
    "internship",
    "intern",
    "volunteer",
    "unpaid",
    "تدريب صيفي",
    "متدرب",
    "متطوع",
    "بدون مقابل",
    "lead generating", "lead generators", "lead generator", "جلب العملاء", "letter writing", "request letter",
}


# Noise: intentionally unscored terms that are too ambiguous to classify.
NOISE_KEYWORDS = {
    "system", "systems",
    "platform", "platforms",
    "api",
    "app", "apps", "application", "applications",
    "user", "users",
    "roles", "permissions",
    "نظام", "أنواع",
    "منصة", "منصات",
    "برنامج", "برامج", "برمجية",
    "موقع", "مواقع",
    "متجر", "متاجر",
    "واجهة", "تكامل", "التوثيق",
    "جوال", "موبايل",
    "المستخدمين",
    "صلاحيات",
}


# Runtime invariant: noise terms must never enter scored vocabulary.
def _all_scored_keywords():
    for polarity in (POSITIVE_KEYWORDS, NEGATIVE_KEYWORDS):
        for category in polarity.values():
            for tier in ("core", "supporting"):
                for kw in category.get(tier, {}):
                    yield kw


_collision = NOISE_KEYWORDS.intersection(_all_scored_keywords())
if _collision:
    raise AssertionError(
        "The following NOISE_KEYWORDS were found inside a scored "
        "(core/supporting) dict — this reintroduces the false-positive/"
        "false-negative bug the tiered model was designed to prevent: "
        f"{sorted(_collision)}"
    )
