# AI/ML Data Science category — tiered classifier vocabulary
#
# Core keywords are strong standalone evidence; supporting keywords require
# aggregation. NOISE_KEYWORDS are excluded from scoring entirely.

# Positive evidence: Machine Learning / Deep Learning / AI / Data Science.
POSITIVE_KEYWORDS = {

    "ml_frameworks": {
        "core": {
            "tensorflow": 9,
            "keras": 8,
            "pytorch": 9,
            "scikit-learn": 9,
            "sklearn": 9,
            "xgboost": 8,
            "lightgbm": 8,
            "catboost": 8,
            "jupyter": 7,
            "jupyter notebook": 7,
            "google colab": 7,
            "colab": 7,
        },
        "supporting": {
            "pandas": 4,
            "numpy": 4,
            "scipy": 4,
            "matplotlib": 4,
            "seaborn": 4,
            "plotly": 4,
            "dataframe": 4,
        },
    },

    "ml_concepts": {
        "core": {
            "machine learning": 9,
            "deep learning": 9,
            "neural network": 8,
            "neural networks": 8,
            "cnn": 7,
            "rnn": 7,
            "lstm": 7,
            # Demoted core->supporting (2026-08-24 audit): bare 'transformer'
            # phantom-fires on electrical-engineering gigs (23 corpus hits:
            # PSU/inverter/SMPS designs, rowid 7890 pure sine wave inverter)
            # producing lone-core arbitration calls that resolve to none.
            # Genuine transformer-model work carries sibling ML vocabulary
            # (nlp/llm/deep learning) and no longer depends on this token.
            "attention mechanism": 7,
            "reinforcement learning": 8,
            "supervised learning": 8,
            "unsupervised learning": 8,
            "semi-supervised learning": 7,
            "self-supervised learning": 7,
            "transfer learning": 8,
            "few-shot learning": 7,
            "zero-shot learning": 7,
            "meta learning": 7,
            "federated learning": 7,
        },
        "supporting": {
            "transformer": 4,
            "regression": 3,
            "classification": 3,
            "clustering": 3,
            "dimensionality reduction": 4,
            "feature engineering": 4,
            "feature selection": 4,
            "hyperparameter tuning": 4,
            "cross validation": 4,
            "train test split": 3,
            "overfitting": 3,
            "underfitting": 3,
            "bias variance": 3,
            "regularization": 3,
        },
    },

    "nlp": {
        "core": {
            "nlp": 8,
            "natural language processing": 8,
            "text classification": 7,
            "sentiment analysis": 7,
            "named entity recognition": 7,
            "ner": 6,
            "text generation": 7,
            "machine translation": 7,
            "text summarization": 7,
            "question answering": 7,
            "text mining": 7,
            "word embedding": 7,
            "word2vec": 7,
            "glove": 6,
            "bert": 7,
            "gpt": 6,
            "llm": 7,
            "large language model": 7,
            "openai": 7,
            "hugging face": 7,
            "langchain": 7,
            "rag": 6,
            "retrieval augmented generation": 7,
            "speech recognition": 7,
            "speaker recognition": 7,
            "voice recognition": 7,
            "speech to text": 7,
        },
        "supporting": {
            "chatgpt": 3,
            "claude": 3,
            "gemini": 3,
            "corpus": 3,
            "corpora": 3,
            "embedding": 3,
            "vector": 3,
            "semantic": 3,
            "syntax": 3,
            "pos tag": 3,
            "chunking": 3,
        },
    },

    "computer_vision": {
        "core": {
            "computer vision": 8,
            "image classification": 7,
            "object detection": 7,
            "image segmentation": 7,
            "semantic segmentation": 7,
            "instance segmentation": 7,
            "face detection": 7,
            "face recognition": 7,
            "ocr": 6,
            "optical character recognition": 6,
            "image processing": 7,
            "video processing": 7,
            "yolo": 7,
            "opencv": 7,
            "pillow": 6,
            "image augmentation": 6,
        },
        "supporting": {
            "cnn": 4,
            "convolutional": 3,
            "pooling": 3,
            "anchor": 3,
            "bounding box": 3,
            "iou": 3,
            "map": 3,
        },
    },

    "data_science": {
        "core": {
            "data science": 9,
            "data scientist": 9,
            "predictive model": 8,
            "predictive modeling": 8,
            "forecasting model": 7,
            "time series": 7,
            "anomaly detection": 7,
            "recommendation system": 7,
            "recommendation engine": 7,
            "experiment design": 7,
            "causal inference": 7,
            "survival analysis": 7,
            "bayesian": 6,
            "bayesian statistics": 7,
            "statistical modeling": 7,
            "statistical analysis": 6,
        },
        "supporting": {
            "eda": 4,
            "exploratory data analysis": 4,
            "hypothesis testing": 4,
            "p-value": 3,
            "confidence interval": 3,
            "regression analysis": 4,
            "correlation": 2,
            "distribution": 2,
        },
    },

    "mlops": {
        "core": {
            "model deployment": 7,
            "model serving": 7,
            "ml pipeline": 7,
            "mlops": 8,
            "model monitoring": 7,
            "model versioning": 6,
            "experiment tracking": 7,
            "mlflow": 7,
            "wandb": 7,
            "neptune": 6,
            "kubeflow": 7,
            # Full name only: bare "airflow" also matches HVAC/CAD prose.
            "apache airflow": 6,
            "prefect": 6,
            "dagster": 6,
        },
        "supporting": {
            "docker": 3,
            "kubernetes": 3,
            "ci/cd": 3,
            "model registry": 4,
            "feature store": 4,
            "data drift": 4,
            "concept drift": 4,
        },
    },

    "ai_general": {
        # Arabic: "smart assistant" carries build intent safely; bare
        # "artificial intelligence" mentions are too often tool references
        # in non-AI gigs, so they only contribute supporting weight.
        "core": {
            "مساعد ذكي": 7,
        },
        "supporting": {
            "ذكاء اصطناعي": 4,
            "الذكاء الاصطناعي": 4,
            "بالذكاء الاصطناعي": 4,
            "والذكاء الاصطناعي": 4,
        },
    },

    "generative_ai": {
        "core": {
            "generative ai": 8,
            "generative ai": 8,
            "diffusion model": 7,
            "stable diffusion": 7,
            "midjourney": 6,
            "dall-e": 6,
            "comfyui": 6,
            "comfy ui": 6,
            "gan": 7,
            "generative adversarial": 7,
            "vae": 6,
            "variational autoencoder": 6,
            "qlora": 6,
            "prompt engineering": 7,
            "prompt design": 6,
            "ai agent": 7,
            "ai agents": 7,
            "autonomous agent": 7,
        },
        "supporting": {
            "lora": 3,
            "fine-tuning": 3,
            "fine tuning": 3,
            "fine-tune": 3,
            "token": 3,
            "tokenization": 3,
            "inference": 3,
            "training": 3,
            "dataset": 2,
            "annotation": 3,
            "labeling": 3,
        },
    },
}


# Negative evidence: other software domains to avoid overlap.
NEGATIVE_KEYWORDS = {

    "community_content": {
        "core": {
            "community manager": 8,
            "community management": 8,
        },
        "supporting": {},
    },

    "frontend": {
        "core": {
            "react": 8,
            "reactjs": 8,
            "react.js": 8,
            "nextjs": 8,
            "next.js": 8,
            "vue": 8,
            "vuejs": 8,
            "vue.js": 8,
            "angular": 8,
            "angularjs": 8,
            "svelte": 8,
            "sveltejs": 8,
            "html": 6,
            "css": 6,
            "scss": 6,
            "sass": 6,
            "tailwind": 6,
            "tailwindcss": 6,
            "bootstrap": 6,
            "material ui": 6,
            "chakra ui": 6,
            "frontend": 7,
            "front-end": 7,
            "front end": 7,
            "landing page": 8,
            "landing pages": 8,
            "portfolio website": 7,
            "personal website": 7,
            "responsive design": 6,
            "responsive web": 6,
            "figma to code": 7,
            "figma to html": 7,
            "figma to react": 7,
            "wordpress": 8,
            "woocommerce": 8,
            "shopify": 8,
            "webflow": 7,
            "wix": 7,
            "elementor": 7,
            "divi": 7,
        },
        "supporting": {
            "javascript": 3,
            "typescript": 3,
            "ui implementation": 4,
            "pixel perfect": 4,
            "browser": 2,
            "web app": 4,
            "web application": 4,
        },
    },

    "backend": {
        "core": {
            "laravel": 8,
            "django": 7,
            "flask": 6,
            "fastapi": 6,
            "spring boot": 8,
            "spring": 7,
            ".net": 7,
            "asp.net": 7,
            "nodejs": 7,
            "node.js": 7,
            "express": 6,
            "nestjs": 7,
            "ruby on rails": 7,
            "ruby": 5,
            "golang": 4,
            "rust": 4,
            "rest api": 6,
            "restful": 6,
            "graphql": 5,
            "grpc": 5,
            "microservice": 6,
            "microservices": 6,
            "api development": 6,
            "api integration": 5,
            "backend": 7,
            "back-end": 7,
            "server side": 6,
        },
        "supporting": {
            "postgresql": 3,
            "mysql": 3,
            "mongodb": 3,
            "redis": 3,
            "elasticsearch": 3,
            "authentication": 2,
            "authorization": 2,
            "oauth": 2,
            "jwt": 2,
            "database design": 3,
            "database schema": 3,
        },
    },

    "mobile": {
        "core": {
            "flutter": 8,
            "dart": 7,
            "react native": 8,
            "swift": 7,
            "swiftui": 7,
            "uikit": 7,
            "kotlin": 7,
            "jetpack compose": 7,
            "android": 6,
            "android studio": 7,
            "ios": 6,
            "iphone": 6,
            "ipad": 6,
            "xcode": 7,
            "mobile app": 7,
            "mobile application": 7,
            "app store": 5,
            "google play": 5,
        },
        "supporting": {
            "cross-platform": 3,
            "cross platform": 3,
            "ionic": 4,
            "capacitor": 4,
            "cordova": 4,
            "firebase": 3,
            "supabase": 3,
        },
    },

    "game": {
        "core": {
            "unity": 8,
            "unity3d": 8,
            "unreal engine": 8,
            "unreal": 7,
            "ue5": 8,
            "ue4": 8,
            "godot": 8,
            "game design": 8,
            "game development": 8,
            "game dev": 7,
            "gameplay": 7,
            "game mechanic": 7,
            "game mechanics": 7,
            "game programmer": 7,
            "game developer": 7,
            "indie game": 7,
            "mobile game": 7,
            "pc game": 6,
            "console game": 6,
            "game prototype": 7,
            "تصميم لعبة": 7,
            "برمجة ألعاب": 7,
            "تطوير ألعاب": 7,
            "مطور ألعاب": 7,
        },
        "supporting": {
            "game level": 3,
            "level design": 3,
            "game world": 3,
            "game ai": 3,
            "npc": 2,
            "inventory system": 2,
            "quest system": 3,
            "dialogue system": 3,
            "game physics": 3,
            "collision detection": 3,
            "game state": 2,
            "game save": 2,
            "save system": 2,
            "game balance": 3,
            "game economy": 3,
            "microtransaction": 2,
            "in-app purchase": 2,
            "game monetization": 3,
        },
    },

    "enterprise": {
        "core": {
            "erp": 7,
            "crm": 7,
            "wms": 7,
            "saas": 6,
            "netsuite": 7,
            "netsuite": 7,
            "business central": 7,
            "dynamics 365": 7,
        },
        "supporting": {
            "mvp": 3,
            "software development": 4,
            "admin panel": 4,
            "control panel": 3,
            "admin dashboard": 4,
            "user management": 4,
            "inventory management": 4,
        },
    },

    "data_analysis": {
        "core": {
            "data analysis": 8,
            "data analyst": 8,
            "power bi": 8,
            "tableau": 8,
            "business intelligence": 7,
            "business analyst": 7,
            "financial analysis": 8,
            "financial analyst": 8,
            "looker": 7,
            "looker studio": 7,
            "qlik": 7,
            "تحليل بيانات": 8,
            "محلل بيانات": 8,
            "تحليل مالي": 8,
        },
        "supporting": {
            "excel": 4,
            "pivot table": 4,
            "dashboard": 3,
            "analytics": 2,
            "kpi": 3,
            "reporting": 2,
            "etl": 3,
        },
    },

    "education": {
        "core": {
            "teach": 7,
            "teaching": 7,
            "teacher": 7,
            "tutor": 7,
            "tutoring": 7,
            "مدرب": 6,
            "تعليم": 6,
            "تعليمي": 6,
            "معلم": 6,
            "مدرس": 6,
        },
        "supporting": {
            "mentor": 3,
            "mentoring": 3,
            "training": 3,
            "course": 3,
            "courses": 3,
            "curriculum": 3,
            "lesson": 2,
            "lessons": 2,
            "student": 2,
            "students": 2,
        },
    },
    "marketing": {
        # Negative-core placement (not HARD_REJECT): these phrases occur
        # inside genuine build scopes; pure-marketing gigs still reject.
        "core": {
            "translation": 8,
            "google ads": 8,
            "facebook ads": 8,
            "digital marketing": 8,
            "lead generation": 8,
            "lead gen": 7,
            "lead generating": 7,
            "lead generator": 7,
            "lead generators": 7,
            "generación de leads": 7,
            "جلب العملاء": 7,
        },
        "supporting": {},
    },
}


# Hard rejects: unrelated work rejected when no positive signal exists.
HARD_REJECT_KEYWORDS = {
    "graphic design",
    "photoshop",
    "illustrator",
    "video editing",
    "motion graphics",
    "backlink",
    "backlinks",
    "link building",
    "copywriting",
    "commission only",
    "عمولة فقط",
    "internship",
    "intern",
    "volunteer",
    "unpaid",
    "تدريب صيفي",
    "متدرب",
    "متطوع",
    "بدون مقابل",
    # Recurring SMM-reseller storefront spam (8 corpus occurrences,
    # all rejected); hard-rejected so reposts don't burn arbitration
    # calls now that store-build collocations became positive cores.
    "خدمات smm",
    "letter writing", "request letter",
}


# Noise: intentionally unscored terms that are too ambiguous to classify.
NOISE_KEYWORDS = {
    "system", "systems",
    "platform", "platforms",
    "api",
    "app", "apps", "application", "applications",
    "user", "users",
    "login", "signup", "session",
    "roles", "permissions",
    "نظام", "أنواع",
    "منصة", "منصات",
    "برنامج", "برامج", "برمجية",
    "موقع", "مواقع",
    "متجر", "متاجر",
    "واجهة", "تكامل", "التوثيق",
    "جوال", "موبايل",
    "المستخدمين",
    "صلاحيات",
}


# Runtime invariant: noise terms must never enter scored vocabulary.
def _all_scored_keywords():
    for polarity in (POSITIVE_KEYWORDS, NEGATIVE_KEYWORDS):
        for category in polarity.values():
            for tier in ("core", "supporting"):
                for kw in category.get(tier, {}):
                    yield kw


_collision = NOISE_KEYWORDS.intersection(_all_scored_keywords())
if _collision:
    raise AssertionError(
        "The following NOISE_KEYWORDS were found inside a scored "
        "(core/supporting) dict — this reintroduces the false-positive/"
        "false-negative bug the tiered model was designed to prevent: "
        f"{sorted(_collision)}"
    )
