# Data Analysis category — tiered classifier vocabulary
#
# Core keywords are strong standalone evidence; supporting keywords require
# aggregation. NOISE_KEYWORDS are excluded from scoring entirely.

# Positive evidence: Data Analysis / Excel / Power BI / SQL / Python-for-data.
POSITIVE_KEYWORDS = {

    "power_bi": {
        "core": {
            "power bi": 10,
            "powerbi": 10,
            "microsoft power bi": 10,
            "pbix": 10,
            "dax": 10,
            "power query": 9,
            "power query editor": 9,
            "power pivot": 8,
            "m query": 8,
            "m code": 7,
            "باور بي": 10,
            "بور بي": 10,
            "داشبورد": 6,
            "ولداشبورد": 6,
            "بلداشبورد": 6,
            "لداشبورد": 6,
            "داش بورد": 6,
            "ولداش بورد": 6,
            "بلداش بورد": 6,
            "لداش بورد": 6,
        },
        "supporting": {
            "dashboard": 2,
            "dashboards": 4,
            "interactive dashboard": 5,
            "measure": 3,
            "measures": 3,
            "calculated column": 3,
            "star schema": 6,
            "data model": 5,
            "data modeling": 5,
            "لوحة تحكم": 2,
            "ولوحة تحكم": 2,
            "بلوحة تحكم": 2,
            "للوحة تحكم": 2,
            "لوحة معلومات": 4,
            "ولوحة معلومات": 4,
            "بلوحة معلومات": 4,
            "للوحة معلومات": 4,
        },
    },

    "excel": {
        "core": {
            "excel": 8,
            "exel": 8,
            "اكسل": 8,
            "إكسل": 8,
            "اكسيل": 8,
            # Arabic prefix variants
            "لاكسل": 8,
            "باكسل": 8,
            "وأكسل": 8,
            "pivot table": 8,
            "pivot tables": 8,
            "vlookup": 8,
            "xlookup": 8,
            "index match": 8,
            "excel workbook": 6,
            "excel sheet": 6,
            "excel file": 6,
            "شيت اكسل": 6,
            "شيت إكسل": 6,
            "ملف اكسل": 6,
            "ملف إكسل": 6,
            "ملف اكسيل": 6,
            "اكسيل شيت": 6,
            "اكسل شيت": 6,
        },
        "supporting": {
            "spreadsheet": 4,
            "workbook": 4,
            "worksheet": 2,
            "sheet": 3,
            "sheets": 4,
            "xlsx": 4,
            "xls": 3,
            "شيت": 3,
            "شيتات": 3,
            "pivot": 2,
            "pivots": 2,
            "pivot views": 3,
            "lookup": 2,
            "remove duplicates": 3,
            "conditional formatting": 3,
            "financial model": 6,
            "financial modeling": 6,
            "google sheets": 4,
        },
    },

    "sql": {
        "core": {},
        "supporting": {
            "sql": 5,
            "sql server": 5,
            "mysql": 4,
            "postgresql": 4,
            "postgres": 4,
            "sqlite": 4,
            "oracle": 4,
            "stored procedure": 4,
            "قاعدة بيانات": 4,
            "database": 2,
            "query": 4,
            "queries": 2,
            "استعلام": 3,
            "استعلامات": 3,
        },
    },

    "data_analysis": {
        "core": {
            "data analysis": 9,
            "data analyst": 9,
            "tableau": 9,
            "business analyst": 8,
            "business intelligence": 8,
            "financial analysis": 9,
            "financial analyst": 9,
            "looker": 7,
            "looker studio": 7,
            "qlik": 7,
            # Sales-analysis concept family: verified genuine DA work
            # (rowids 1818 accepted / 8043+8046 missed pair / 2684 accepted).
            # Definite form promoted from supporting: same concept class.
            "تحليل مبيعات": 9,
            "تحليل المبيعات": 9,
            # Attached-prefix surface form (لـ) seen in production titles.
            "لتحليل مبيعات": 9,
            "sales analysis": 7,
            "sales dashboard": 7,
            "sales dashboards": 7,
            "تحليل بيانات": 9,
            "محلل بيانات": 9,
            "تحليل مالي": 9,
            "تابلو": 8,
            "analisis data": 9,
            # Arabic prefix variants: و/ب/ل/ك attached to word root
            "وتحليل بيانات": 9,
            "بتحليل بيانات": 9,
            "لتحليل بيانات": 9,
            "بمحلل بيانات": 9,
            "لمحلل بيانات": 9,
            "وتحليل مالي": 9,
            "بتحليل مالي": 9,
            "لتحليل مالي": 9,
            # Descriptive/business statistical-analysis work (ANOVA, SPSS,
            # hypothesis testing, R stats) is Data Analysis, NOT AI/ML
            # model-building. 2026-09-02 run 31: 12655 (ANOVA on Citrus
            # Virus Dataset) and 12682 (Seven mini SPSS projects) were
            # wrongly claimed by ai_ml via its over-broad 'statistical
            # analysis' core and suppressed. These cores make the
            # data_analysis candidate fire so the jobs route here instead.
            "anova": 8,
            "spss": 8,
            "statistical analysis": 7,
            "statistical analyses": 7,
            "hypothesis testing": 6,
            "statistical testing": 6,
            "statistical test": 6,
            "post-hoc": 6,
            "post hoc": 6,
        },
        "supporting": {
            "analytics": 2,
            "analysis": 3,
            "sales report": 4,
            "sales reporting": 4,
            "marketing analysis": 4,
            "market analysis": 4,
            "customer analysis": 4,
            "hr analysis": 4,
            "forecast": 3,
            "forecasting": 3,
            "budgets": 3,
            "cash flow": 4,
            "budget analysis": 4,
            "kpi": 3,
            "kpis": 3,
            "metrics": 2,
            "visualization": 3,
            "data visualization": 4,
            "report": 1,
            "reports": 1,
            "reporting": 2,
            "etl": 3,
            "data cleaning": 4,
            "excel dashboard": 5,
            "executive dashboard": 4,
            "dashboard design": 3,
            "business metrics": 3,
            "data transformation": 4,
            "transform data": 3,
            "fact table": 4,
            "dimension table": 4,
            "snowflake schema": 4,
            "cohort analysis": 4,
            "customer segmentation": 4,
            "data validation": 3,
            "data curation": 3,
            "data quality": 3,
            "pivot chart": 3,
            "dataset": 5,
            "datasets": 4,
            # Arabic: "data display" — Arabic dashboard briefs aggregate
            # dataset/dashboard/البيانات to the supporting threshold.
            "عرض البيانات": 5,
            "clean data": 4,
            "cleaning data": 4,
            "prepare data": 3,
            "data preparation": 3,
            "preprocessing": 3,
            "preprocess": 3,
            "clean dataset": 4,

            "تحليل السوق": 4,
            "تحليل الأعمال": 4,
            "ذكاء الأعمال": 4,
            "تقارير": 2,
            "تقرير": 1,
            "مؤشرات الأداء": 3,
            "مؤشر أداء": 3,
            "مؤشرات": 2,
            "تنظيف البيانات": 4,
            "وتنظيف البيانات": 4,
            "بتنظيف البيانات": 4,
            "لتنظيف البيانات": 4,
            "التنبؤ": 3,
            "لوحة بيانات": 3,
            "لوحة مؤشرات": 3,
            "تحويل البيانات": 3,
            "معالجة البيانات": 3,
            "بيانات": 1,
            "البيانات": 1,
            "داتا": 2,
            "الداتا": 2,
            "فرز": 2,
            "فلترة": 2,
            "دمج البيانات": 2,
            "تنسيق البيانات": 2,
            "ترتيب البيانات": 2,
            "استخراج البيانات": 3,
            "تنظيف الداتا": 4,
            "وتنظيف الداتا": 4,
            "بتنظيف الداتا": 4,
            "لتنظيف الداتا": 4,
            "تجهيز الداتا": 3,
            "وتجهيز الداتا": 3,
            "بتجهيز الداتا": 3,
            "لتجهيز الداتا": 3,
            "تنظيف": 2,
            "تنضيف": 2,
            "ينظف": 2,
            "تنقية": 2,
            "جودة البيانات": 3,
            "التحقق من صحة البيانات": 3,
            "تجهيز البيانات": 3,
            "تهيئة البيانات": 3,
            "تحضير البيانات": 3,
            "تجهيز": 1,
            "تهيئة": 1,
            "تحضير": 1,
            "تحليل": 1,
            "للتحليل": 2,
        },
    },

    "python": {
        "core": {
            "pandas": 8,
            "numpy": 6,
            "dataframe": 6,
            "polars": 6,
            "openpyxl": 6,
            "xlwings": 6,
        },
        "supporting": {
            "python": 3,
            "matplotlib": 4,
            "plotly": 4,
            "seaborn": 4,
            "jupyter": 4,
            "notebook": 3,
            "etl": 3,
            "csv": 2,
            "json": 1,
            "data processing": 4,
            "data pipeline": 4,
        },
    },
}



# Negative evidence: software engineering, automation, enterprise, and other non-DA domains.
NEGATIVE_KEYWORDS = {

    "web": {
        "core": {
            "wordpress": 9,
            "woocommerce": 8,
            "shopify": 8,
            "webflow": 7,
            "wix": 7,
            "react": 8,
            "reactjs": 8,
            "next.js": 8,
            "nextjs": 8,
            "vue": 8,
            "angular": 8,
            "svelte": 8,
            "landing page": 8,
            "landing pages": 8,
            "landingpage": 8,
            "portfolio website": 7,
            "personal website": 7,
            "resume website": 7,
            "cv website": 7,
            "موقع إلكتروني": 7,
            "موقع الكتروني": 7,
            "متجر إلكتروني": 8,
            "متجر الكتروني": 8,
            "صفحة هبوط": 8,
            "لاندنج بيج": 8,
            "موقع شخصي": 7,
        },
        "supporting": {
            "javascript": 3,
            "typescript": 3,
            "bootstrap": 2,
            "tailwind": 2,
            "frontend": 4,
            "web application": 4,
            "framer": 4,
            "elementor": 4,
            "تطوير موقع": 4,
            "تطوير مواقع": 4,
            "مطور ويب": 4,
            "مطور مواقع": 4,
            "تطبيق ويب": 4,
            "بورتفوليو": 3,
            "معرض أعمال": 3,
        },
    },

    "backend": {
        "core": {
            "laravel": 8,
            "django": 7,
            "spring boot": 8,
            "spring": 7,
            ".net": 7,
            "asp.net": 7,
            "nestjs": 7,
            "full stack": 9,
            "fullstack": 9,
            "مطور تطبيقات": 7,
            "database recovery": 6,
            "restore backup": 6,
            "backup restore": 6,
            "corrupted database": 6,
            "database dump": 5,
            "access control": 6,
            "audit logging": 6,
            "role-based access": 6,
            "encryption": 6,
            "إصلاح أخطاء": 6,
            "مبرمج محترف": 7,
            "custom database": 6,
            "database solution": 6,
            # Database ADMINISTRATION (DBA upkeep) is not analysis work;
            # prevents SQL-DBA gigs from becoming spurious DA candidates
            # via generic sql/database supportings (rowid 8097).
            "dba": 6,
        },
        "supporting": {
            "flask": 3,
            "fastapi": 4,
            "node": 4,
            "nodejs": 4,
            "express": 4,
            "backend": 5,
            "rest api": 4,
            "graphql": 3,
            "crud": 2,
            "authentication": 2,
            "authorization": 2,
            "c++": 3,
            "cpp": 3,
            "employee record": 3,
            "web-view": 2,
            "sqlite": 2,
            "برمجة": 3,
            "مبرمج": 4,
            "مطور": 4,
            # Supporting, not core: this phrase is also the Mostaql channel
            # poster-badge line (client tag), not a deliverable statement.
            "مهندس برمجيات": 4,
            "واجهة برمجية": 4,
            "واجهات برمجية": 4,
            "تكامل api": 4,
            "ربط api": 4,
            "واجهة خلفية": 4,
            "تسجيل دخول": 2,
            "المصادقة": 2,
            "user registration": 3,
            "registration module": 4,
            "user authentication": 3,
            "نظام تسجيل": 3,
            "تسجيل مستخدمين": 3,
            "إنشاء حساب": 3,
            "استعادة نسخة احتياطية": 4,
            "استرجاع قاعدة البيانات": 4,
            "نسخ احتياطي": 3,
            "التحكم بالصلاحيات": 4,
            "التشفير": 4,
            "الامتثال": 3,
            "سجل التدقيق": 4,
        },
    },

    "mobile": {
        "core": {
            "flutter": 8,
            "react native": 8,
            "swift": 6,
            "kotlin": 6,
            "تطبيق اندرويد": 7,
            "تطبيق أندرويد": 7,
            "تطبيق ايفون": 7,
            "تطبيق ios": 7,
        },
        "supporting": {
            "android": 4,
            "ios": 4,
            "mobile application": 4,
            "application development": 3,
            "تطبيق جوال": 4,
            "تطبيق موبايل": 4,
            "اندرويد": 3,
            "أندرويد": 3,
            "ايفون": 3,
        },
    },

    "design": {
        "core": {
            "ui designer": 6,
            "ux designer": 6,
            "figma": 5,
        },
        "supporting": {
            "تصميم واجهات": 3,
            "واجهة مستخدم": 3,
            "واجهة أمامية": 3,
        },
    },

    "education": {
        "core": {
            "teach": 8,
            "teaching": 8,
            "teacher": 8,
            "tutor": 8,
            "tutoring": 8,
            "مدرب": 7,
            "تعليم": 7,
            "تعليمي": 7,
            "معلم": 7,
            "مدرس": 7,
            # Arabic prefix variants
            "لتعليم": 7,
            "بتعليم": 7,
            "وتعليم": 7,
            "لتعليمي": 7,
            "بتعليمي": 7,
            "وتعليمي": 7,
            "لمعلم": 7,
            "بمعلم": 7,
            "ومعلم": 7,
            "لمدرس": 7,
            "بمدرس": 7,
            "ومدرس": 7,
        },
        "supporting": {
            "mentor": 4,
            "mentoring": 4,
            "training": 4,
            "coach": 3,
            "coaching": 3,
            "course": 4,
            "courses": 4,
            "curriculum": 4,
            "syllabus": 4,
            "lesson": 3,
            "lessons": 3,
            "learning": 1,
            "learn": 1,
            "student": 3,
            "students": 3,
            "assignment": 2,
            "assignments": 2,
            "school": 3,
            "classroom": 3,
            "quiz": 2,
            "pupil": 3,
            "educational": 2,
            "learning styles": 3,
            "kinesthetic": 2,
            "bilingual": 2,
            "试题": 2,
            "تدريب": 4,
            "تعلم": 3,
            "شرح": 3,
            "دورة": 4,
            "دورات": 4,
            "كورس": 4,
            "طالب": 3,
            "طلاب": 3,
            "منصة تعليمية": 3,
        },
    },

    "enterprise": {
        # CRM integration/customization builds are legitimate work
        # (customization IS work for a linked business function).
        # 'crm' demoted core->supporting (2026-08-29 audit): the core
        # token was title-killing the whole WhatsApp/CRM/AI-bot class
        # (e.g. rowid 10758, a WhatsApp AI-bot + CRM build).
        "core": {
            "erp": 8,
            "wms": 8,
            "saas": 6,
            "netsuite": 7,
            "suitescript": 7,
            "suiteflow": 7,
            "erp integration": 6,
            "payroll platform": 6,
            "payroll system": 6,
            "billing software": 6,
            "billing system": 6,
            "business central": 7,
            "dynamics 365": 7,
            "dolibarr": 7,
        },
        "supporting": {
            "crm": 4,
            "mvp": 3,
            "software development": 4,
            "admin panel": 4,
            "control panel": 3,
            "admin dashboard": 4,
            "user management": 4,
            "hrm": 5,
            "pos": 4,
            "inventory": 1,
            "inventory management": 5,
            "checkout": 3,
            "payment gateway": 4,
            "shopping cart": 4,
            "product catalog": 3,
            "تطوير منصة": 4,
            "ساس": 4,
            "منصة إلكترونية": 4,
            "منصة الكترونية": 4,
            "منصة حجز": 4,
            "مشروع ناشئ": 3,
            "شركة ناشئة": 3,
            "نظام سحابي": 3,
            "لوحة تحكم إدارية": 4,
            "لوحة إدارة": 4,
            "لوحة تحكم للمشرف": 4,
            "لوحة المشرف": 4,
            "لوحة الأدمن": 4,
            "لوحة المدير": 3,
            "إدارة المستخدمين": 4,
            "تكامل الأنظمة": 4,
            "نظام رواتب": 4,
            "منصة رواتب": 4,
            "برنامج فوترة": 4,
            "نظام فوترة": 4,
        },
    },

    "nocode": {
        "core": {
            "base44": 8,
            "bubble.io": 7,
            "bubble": 6,
            "power apps": 7,
            "power automate": 7,
        },
        "supporting": {
            "no-code": 4,
            "nocode": 4,
            "low-code": 4,
            "glide": 3,
            "adalo": 3,
            "بدون كود": 4,
            "بدون برمجة": 4,
            "لو كود": 4,
            "منخفض الكود": 4,
            "نوكود": 4,
        },
    },

    "ai_apps": {
        # AI apps / chatbot / WhatsApp-integration builds are
        # legitimate work. These tokens still deflate data_analysis
        # claims for AI-app building posts, but can no longer core-kill
        # them at the title/body level (2026-08-29 audit: core
        # 'whatsapp'/'واتساب' deterministically rejected the whole
        # WhatsApp-bot/AI-chatbot class, e.g. rowid 10758).
        "core": {},
        "supporting": {
            "whatsapp": 3,
            "واتساب": 3,
            "لواتساب": 3,
            "بواتساب": 3,
            "وواتساب": 3,
            "llm": 2,
            "chatbot": 3,
            "rag": 2,
            "openai api": 2,
            "gemini api": 2,
        },
    },

    "devops": {
        "core": {},
        "supporting": {
            "docker": 2,
            "kubernetes": 3,
            "nginx": 2,
            "linux server": 2,
            "سيرفر": 2,
            "استضافة": 2,
            "رفع الموقع": 2,
        },
    },

    "automation": {
        "core": {
            "data entry": 6,
            "ادخال بيانات": 6,
            "إدخال بيانات": 6,
            "وإدخال بيانات": 6,
            "بإدخال بيانات": 6,
            "لإدخال بيانات": 6,
            "address entry": 6,
            "data transfer": 6,
            "text transfer": 6,
            "extract pdf text": 6,
            "نقل البيانات": 6,
            "نقل بيانات": 6,
            "ونقل البيانات": 6,
            "بنقل البيانات": 6,
            "لنقل البيانات": 6,
            "ونقل بيانات": 6,
            "بنقل بيانات": 6,
            "لنقل بيانات": 6,
            "web scraping": 6,
            "scraping": 6,
            "scraper": 6,
            "scrapers": 6,
            "extract pdf tables": 6,
            "pdf tables": 5,
            "pdf table": 5,
            "tabular data": 5,
            "data to excel": 6,
            "browser extension": 7,
            "chrome extension": 7,
            "إضافة متصفح": 7,
            "إضافات كروم": 7,
            "ocr": 6,
            "pdf to excel": 6,
            "pdf to excel conversion": 6,
            "pdf table conversion": 5,
            "extract tables": 5,
            "csv to spreadsheet": 6,
            "data extraction": 6,
            "transcribe": 6,
            "transcription": 6,
            "transcribed": 6,
            "test automation": 6,
            "نموذج فاتورة": 6,
            "mail merge": 6,
            "microsoft word": 6,
            "word documents": 6,
            "online survey": 6,
            "survey creation": 6,
            "typeform": 6,
            "google forms": 6,
            "freshworks": 6,
            "excel troubleshooting": 6,
            "automated trading": 6,
            "algorithmic trading": 6,
            "quantitative trading": 6,
            "stock market scanner": 6,
            "market scanner": 6,
            "stock scanner": 6,
            "stock screener": 6,
            "pricefx": 6,
            "selenium": 6,
            "image to excel": 6,
            "jmeter": 6,
            "skills assessment": 6,
            "copy and paste": 6,
            "screenshot text to excel": 6,
            "macro automation": 6,
            "تصميم شيت": 6,
        },
        "supporting": {
            "browser automation": 4,
            "automation tool": 3,
            "desktop application": 4,
            "playwright": 4,
            "qa": 4,
            "tester": 3,
            "electron": 3,
            "digital twin": 4,
            "revit": 3,
            "bim": 3,
            "hvac": 3,
            "energyplus": 4,
            "generative ai": 4,
            "semantic search": 4,
            "document ingestion": 4,
            "vector database": 4,
            "retrieval augmented generation": 5,
            "ai agent": 4,
            "ai agents": 4,
            "emergent": 4,
        },
    },

    "cad": {
        "core": {
            "3d modelling": 7,
            "3d modeling": 7,
            "3d model": 6,
            "3d models": 6,
            "autodesk inventor": 8,
            "inventor assembly": 8,
            "inventor format": 8,
            "solidworks": 8,
            "autocad": 8,
            "fusion 360": 8,
            "cnc": 6,
            "shop drawings": 7,
            "tekla": 8,
        },
        "supporting": {},
    },

    "marketing": {
        "core": {
            # Negative-core placement (not HARD_REJECT): these phrases occur
            # inside genuine build scopes; pure-marketing gigs still reject.
            "translation": 8,
            "google ads": 8,
            "facebook ads": 8,
            "digital marketing": 8,
            "lead generation": 8,
            "lead gen": 7,
            "lead generating": 7,
            "lead generator": 7,
            "lead generators": 7,
            "generación de leads": 7,
            "جلب العملاء": 7,
            "content creator": 6,
            "content creators": 6,
            "influencer": 6,
            "influencers": 6,
            "followers": 6,
            "صانع محتوى": 6,
            "صناع محتوى": 6,
            "صناع المحتوى": 6,
            "متابعين": 6,
        },
        "supporting": {},
    },

    "writing": {
        "core": {
            "scientific article": 7,
            "academic writing": 7,
            "manuscript": 6,
            "peer reviewed": 6,
        },
        "supporting": {
            "research paper": 4,
            "academic paper": 4,
        },
    },
}



# Hard rejects: unrelated work rejected when no positive signal exists.
HARD_REJECT_KEYWORDS = {
    "graphic design",
    "photoshop",
    "illustrator",
    "video editing",
    "motion graphics",
    "backlink",
    "backlinks",
    "link building",
    "copywriting",
    "commission only",
    "عمولة فقط",
    "internship",
    "intern",
    "volunteer",
    "unpaid",
    "تدريب صيفي",
    "متدرب",
    "متطوع",
    "بدون مقابل",
    "data entry",
    "مدخل بيانات",
    "ومدخل بيانات",
    "بمدخل بيانات",
    "لمدخل بيانات",
    # Gmail automation/export gigs are email tooling, not analysis work.
    "gmail",
    # CAD product names: spreadsheet/BOM deliverables make these gigs look
    # DA-adjacent, but the work is mechanical CAD, never analysis.
    "solidworks", "autocad", "fusion 360",
    # Recurring SMM-reseller storefront spam (8 corpus occurrences, all
    # rejected); hard-rejected so reposts don't burn arbitration calls.
    "خدمات smm",
    "letter writing", "request letter",
    # Gambling/real-money gaming products are out of scope (policy block).
    "gambling", "casino", "igaming", "jackpot", "poker", "roulette",
    "blackjack", "sportsbook", "sports betting", "slot machine",
    # lottery/lotto added 2026-08-28 run 20: full-corpus sweep found 1
    # historical ACCEPTED 'Automated Lottery' backend job (rowid 8863);
    # unambiguous gambling, 0 window / 0 corpus innocent collateral.
    "lottery", "lotto",
    # Adult/18+ web-content products are out of scope (policy block,
    # 2026-08-29 run 22). freelancer:40677922 'Website Development'
    # (porn site build modelled on beeg.com: uploader roles, paysite
    # tags, VR player) was keyword_direct NOTIFIED as frontend/full_stack
    # and DELIVERED -- fp_delivered. Full-corpus: these tokens have 0
    # accepted collateral in any category (historical adult/escort jobs
    # all already rejected). 'nsfw' added 2026-08-29 run 23 -- full-corpus
    # impact is exactly 2 jobs: freelancer:40660265 (ai_ml, ACCEPTED
    # pre-policy, explicit PG violation: 'AI mini-series ... along with
    # NSFW variants') and freelancer:40641766 (already rejected); both
    # llm-arbitrated so replay-safe.
    "porn", "paysite", "paysites", "beeg", "nsfw",
    "adult site", "adult website",
    "escort service", "escort services",
    # companion-rental / rental-boyfriend / escort-style booking platforms are
    # adult-adjacent and OUT OF SCOPE (2026-09-02 run 31). full_stack delivered
    # FPs 12635/12717 + rejected siblings 12329/12602/12692. Narrow phrases
    # only (deliberately NOT bare 'companion'/'escort' - care-companion /
    # dating collateral risk).
    "rental boyfriend", "boyfriend rental", "rent-a-boyfriend",
    "rental companion", "companion rental",
    "betting", "wager", "wagering",
    "1xbet", "dragon tiger", "dragon vs tiger",
    "quotex", "iq option", "binary options", "olymptrade", "pocket option",
    # Crash/binary-Gambling variant phrases wrapped in benign-sounding
    # reward/spin language (2026-09-03 run 32). spin-win/lucky-jet/satta-matka
    # were missing here but present in frontend/backend/game_dev - a job naming
    # these would slip past data_analysis/ai_ml hard-reject. All unambiguous
    # gambling; 0 expected window/corpus innocent collateral.
    "spin and win", "spin win", "lucky jet", "satta matka",
    # PCB/hardware engineering misfires reach data_analysis via analytics vocab.
    "pcb",
    # Hardware/IoT/firmware manufacturing is out of scope (same rationale
    # as mobile_app).  Rowid 13128 contains these phrases literally;
    # hard-rejecting avoids wasting Gemini API calls.
    "wearable electronics", "embedded firmware",
}



# Noise: intentionally unscored terms that are too ambiguous to classify.
NOISE_KEYWORDS = {
    "system", "systems",
    "platform", "platforms",
    "api",
    "app", "apps", "application", "applications",
    "website", "web app", "webapp",
    "user", "users",
    "ui", "ux",
    "login", "signup", "session",
    "oauth", "jwt",
    "roles", "permissions",
    "نظام", "أنظمة",
    "منصة", "منصات",
    "تطبيق", "تطبيقات", "برنامج", "برامج", "برمجية",
    "موقع", "مواقع",
    "متجر", "متاجر",
    "واجهة", "تكامل", "التوثيق",
    "جوال", "موبايل",
    "المستخدمين",
    "صلاحيات",
}



# Runtime invariant: noise terms must never enter scored vocabulary.
def _all_scored_keywords():
    for polarity in (POSITIVE_KEYWORDS, NEGATIVE_KEYWORDS):
        for category in polarity.values():
            for tier in ("core", "supporting"):
                for kw in category.get(tier, {}):
                    yield kw


_collision = NOISE_KEYWORDS.intersection(_all_scored_keywords())
if _collision:
    raise AssertionError(
        "The following NOISE_KEYWORDS were found inside a scored "
        "(core/supporting) dict — this reintroduces the false-positive/"
        "false-negative bug the tiered model was designed to prevent: "
        f"{sorted(_collision)}"
    )
