INTEREST_CATEGORIES = {
    "power_bi": {
        "power bi": 50,
        "powerbi": 50,
        "dashboard": 30,
        "dashboards": 30,
        "pbix": 60,
        "dax": 50,
        "power query": 40,
        "لوحة تحكم": 30,
        "لوحة معلومات": 30,
        "داشبورد": 30,
        "باور بي": 50,
    },

    "excel": {
        "excel": 30,
        "اكسل": 30,
        "إكسل": 30,
        "spreadsheet": 20,
        "pivot table": 30,
        "pivot": 15,
        "power pivot": 30,
        "vlookup": 25,
        "xlookup": 25,
        "index match": 25,
        "google sheets": 20,
    },

    "sql": {
        "sql": 25,
        "mysql": 20,
        "postgresql": 20,
        "postgres": 20,
        "sqlite": 20,
        "oracle": 20,
        "database": 15,
        "query": 10,
        "queries": 10,
        "قاعدة بيانات": 20,
        "استعلام": 20,
    },

    "data_analysis": {
        "تحليل بيانات": 40,
        "محلل بيانات": 40,
        "data analysis": 40,
        "data analyst": 40,
        "business analyst": 35,
        "analytics": 25,
        "analysis": 20,
        "business intelligence": 35,
        "ذكاء الأعمال": 35,
        "report": 10,
        "reports": 10,
        "reporting": 15,
        "تقارير": 15,
    },

    "portfolio": {
        "portfolio": 35,
        "portfolio website": 50,
        "personal website": 40,
        "landing page": 30,
        "resume website": 40,
        "cv website": 40,
        "موقع شخصي": 40,
        "بورتفوليو": 50,
        "معرض أعمال": 40,
        "صفحة هبوط": 30,
    },

    "python": {
        "python": 20,
        "automation": 20,
        "script": 15,
        "scripting": 15,
        "pandas": 30,
        "numpy": 25,
        "selenium": 20,
        "beautifulsoup": 20,
        "web scraping": 25,
    },
}

HARD_REJECT_KEYWORDS = {
    "flutter",
    "react native",
    "android",
    "ios",
    "swift",
    "kotlin",
    "graphic design",
    "logo",
    "photoshop",
    "illustrator",
    "video editing",
    "motion graphics",
    "translation",
    "seo",
    "digital marketing",
}

SOFT_NEGATIVE_KEYWORDS = {
    "wordpress": -40,
    "woocommerce": -40,
    "shopify": -40,
    "laravel": -30,
}
