# Game Development category — tiered classifier vocabulary
#
# Core keywords are strong standalone evidence; supporting keywords require
# aggregation. NOISE_KEYWORDS are excluded from scoring entirely.

# Positive evidence: Game Development / Unity / Unreal / Godot / Game Design.
POSITIVE_KEYWORDS = {

    "game_engines": {
        "core": {
            "unity": 9,
            "unity3d": 9,
            "unreal engine": 9,
            "unreal": 8,
            "ue5": 9,
            "ue4": 9,
            "godot": 9,
            "cryengine": 8,
            "game maker": 8,
            "gamemaker": 8,
            "defold": 7,
            "cocos2d": 8,
            "cocos creator": 8,
            "phaser": 7,
            "pixi.js": 6,
        },
        "supporting": {
            # English prose verb ("construct sentences") and generic
            # platform word ("steam room"); not reliable engine evidence.
            "construct": 3,
            "game engine": 4,
            "2d game": 4,
            "3d game": 4,
            "game framework": 4,
            "rendering engine": 4,
        },
    },

    "game_design": {
        "core": {
            "game design": 9,
            "game development": 9,
            "game dev": 8,
            "gameplay": 8,
            "game mechanic": 8,
            "game mechanics": 8,
            "game programmer": 8,
            "game developer": 8,
            "indie game": 8,
            "mobile game": 8,
            "pc game": 7,
            "console game": 7,
            "game prototype": 8,
            "game system": 7,
            "game loop": 7,
            "game architecture": 8,
            "roblox": 8,
            "تصميم لعبة": 8,
            "برمجة ألعاب": 8,
            "تطوير ألعاب": 8,
            "مطور ألعاب": 8,
            # Arabic singular-object build verbs.
            "تطوير لعبة": 8,
            "بناء لعبة": 8,
            "انشاء لعبة": 8,
            "مبرمج ألعاب": 8,
        },
        "supporting": {
            "game level": 4,
            "level design": 4,
            "game world": 4,
            "game ai": 4,
            "npc": 3,
            "inventory system": 3,
            "quest system": 4,
            "dialogue system": 4,
            "game physics": 4,
            "collision detection": 4,
            "game state": 3,
            "game save": 3,
            "save system": 3,
            "game balance": 4,
            "game economy": 4,
            "microtransaction": 3,
            "in-app purchase": 3,
            "game monetization": 4,
        },
    },

    "programming_languages": {
        "core": {
            "gdscript": 9,
            "visual scripting": 7,
        },
        "supporting": {
            "blueprint": 3,
            "c++": 3,
            "c#": 3,
            "lua": 3,
            "haxe": 3,
            "rust": 3,
            "swift": 3,
            "kotlin": 3,
            "java": 3,
        },
    },

    "art_and_models": {
        "core": {
            "blender": 8,
            "maya": 7,
            "3ds max": 7,
            "zbrush": 8,
            "substance painter": 7,
            "substance designer": 7,
            "spine": 7,
            "dragonbones": 7,
        },
        "supporting": {
            "3d model": 3,
            "3d modeling": 3,
            "3d modelling": 3,
            "sprite": 3,
            "animation": 2,
            "character design": 4,
            "environment art": 4,
            "texture": 2,
            "uv mapping": 3,
            "rigging": 3,
            "skin": 2,
            "pixel art": 4,
            "concept art": 4,
        },
    },

    "game_specific": {
        "core": {
            "shader": 7,
            "particle system": 6,
            "particle effect": 6,
            "game asset": 6,
            "game assets": 6,
            "game ui": 6,
            "game hud": 6,
            "game audio": 6,
            "game sound": 6,
            "game music": 6,
            "game trailer": 6,
            "game marketing": 6,
            "game publishing": 6,
            "itch.io": 6,
            "playstation": 5,
            "xbox": 5,
            "nintendo": 5,
            "vr game": 7,
            "ar game": 7,
            "virtual reality game": 7,
            "augmented reality game": 7,
            "metaverse": 5,
        },
        "supporting": {
            "steam": 3,
            "vfx": 3,
            "visual effects": 3,
            "google play": 3,
            "app store": 3,
            "switch": 3,
            "multiplayer": 3,
            "online multiplayer": 4,
            "matchmaking": 3,
            "leaderboard": 3,
            "achievement": 2,
            "tutorial": 2,
            "onboarding": 2,
            "retention": 2,
            "engagement": 2,
            "daily active": 3,
            "churn": 3,
            "monetization": 3,
            "ad revenue": 3,
            "in-game": 3,
        },
    },
}


# Negative evidence: other software domains to avoid overlap.
NEGATIVE_KEYWORDS = {

    # Community/server-setup gigs name the game but deliver no game dev.
    "community_ops": {
        "core": {
            "discord": 6,
        },
        "supporting": {},
    },

    "frontend": {
        "core": {
            "react": 8,
            "reactjs": 8,
            "react.js": 8,
            "nextjs": 8,
            "next.js": 8,
            "vue": 8,
            "vuejs": 8,
            "vue.js": 8,
            "angular": 8,
            "angularjs": 8,
            "svelte": 8,
            "sveltejs": 8,
            "html": 6,
            "css": 6,
            "scss": 6,
            "sass": 6,
            "tailwind": 6,
            "tailwindcss": 6,
            "bootstrap": 6,
            "material ui": 6,
            "chakra ui": 6,
            "frontend": 7,
            "front-end": 7,
            "front end": 7,
            "landing page": 8,
            "landing pages": 8,
            "portfolio website": 7,
            "personal website": 7,
            "responsive design": 6,
            "responsive web": 6,
            "figma to code": 7,
            "figma to html": 7,
            "figma to react": 7,
            "wordpress": 8,
            "woocommerce": 8,
            "shopify": 8,
            "webflow": 7,
            "wix": 7,
            "elementor": 7,
            "divi": 7,
        },
        "supporting": {
            "javascript": 3,
            "typescript": 3,
            "ui implementation": 4,
            "pixel perfect": 4,
            "browser": 2,
            "web app": 4,
            "web application": 4,
        },
    },

    "backend": {
        "core": {
            "laravel": 8,
            "django": 7,
            "flask": 6,
            "fastapi": 6,
            "spring boot": 8,
            "spring": 7,
            ".net": 7,
            "asp.net": 7,
            "nodejs": 7,
            "node.js": 7,
            "express": 6,
            "nestjs": 7,
            "ruby on rails": 7,
            "ruby": 5,
            "golang": 4,
            "rust": 4,
            "rest api": 6,
            "restful": 6,
            "graphql": 5,
            "grpc": 5,
            "microservice": 6,
            "microservices": 6,
            "api development": 6,
            "api integration": 5,
            "backend": 7,
            "back-end": 7,
            "server side": 6,
        },
        "supporting": {
            "postgresql": 3,
            "mysql": 3,
            "mongodb": 3,
            "redis": 3,
            "elasticsearch": 3,
            "authentication": 2,
            "authorization": 2,
            "oauth": 2,
            "jwt": 2,
            "database design": 3,
            "database schema": 3,
        },
    },

    "mobile": {
        "core": {
            "flutter": 8,
            "dart": 7,
            "react native": 8,
            "swift": 7,
            "swiftui": 7,
            "uikit": 7,
            "kotlin": 7,
            "jetpack compose": 7,
            "android": 6,
            "android studio": 7,
            "ios": 6,
            "iphone": 6,
            "ipad": 6,
            "xcode": 7,
            "mobile app": 7,
            "mobile application": 7,
            "app store": 5,
            "google play": 5,
        },
        "supporting": {
            "cross-platform": 3,
            "cross platform": 3,
            "ionic": 4,
            "capacitor": 4,
            "cordova": 4,
            "firebase": 3,
            "supabase": 3,
        },
    },

    "web": {
        "core": {
            "website": 6,
            "web development": 7,
            "web developer": 7,
            "web design": 6,
            "web app": 6,
            "web application": 6,
            "تطوير موقع": 6,
            "تطوير مواقع": 6,
            "مطور ويب": 6,
            "مطور مواقع": 6,
            "موقع إلكتروني": 6,
            "موقع الكتروني": 6,
        },
        "supporting": {
            "seo": 3,
            "search engine": 2,
            "domain": 2,
            "hosting": 2,
            "ssl": 2,
            "cms": 3,
        },
    },

    "enterprise": {
        "core": {
            "erp": 7,
            "crm": 7,
            "wms": 7,
            "saas": 6,
            "netsuite": 7,
            "netsuite": 7,
            "business central": 7,
            "dynamics 365": 7,
        },
        "supporting": {
            "mvp": 3,
            "software development": 4,
            "admin panel": 4,
            "control panel": 3,
            "admin dashboard": 4,
            "user management": 4,
            "inventory management": 4,
        },
    },

    "data_analysis": {
        "core": {
            "data analysis": 8,
            "data analyst": 8,
            "power bi": 8,
            "tableau": 8,
            "business intelligence": 7,
            "business analyst": 7,
            "financial analysis": 8,
            "financial analyst": 8,
            "looker": 7,
            "looker studio": 7,
            "qlik": 7,
            "تحليل بيانات": 8,
            "محلل بيانات": 8,
            "تحليل مالي": 8,
        },
        "supporting": {
            "excel": 4,
            "pivot table": 4,
            "dashboard": 3,
            "analytics": 2,
            "kpi": 3,
            "reporting": 2,
            "etl": 3,
        },
    },

    "ai_ml": {
        "core": {
            "machine learning": 8,
            "deep learning": 8,
            "neural network": 7,
            "tensorflow": 8,
            "keras": 7,
            "pytorch": 8,
            "scikit-learn": 8,
            "sklearn": 8,
            "nlp": 7,
            "natural language processing": 7,
            "computer vision": 7,
            "llm": 7,
            "large language model": 7,
            "openai": 7,
            "gpt": 6,
            "data science": 8,
            "data scientist": 8,
            "predictive model": 7,
            "forecasting model": 7,
            "recommendation system": 7,
            "recommendation engine": 7,
        },
        "supporting": {
            "chatgpt": 3,
            "transformer": 3,
            "regression": 3,
            "classification": 3,
            "clustering": 3,
            "random forest": 4,
            "xgboost": 4,
            "lightgbm": 4,
            "hugging face": 4,
            "langchain": 4,
            "rag": 3,
            "fine-tuning": 4,
            "fine tuning": 4,
            "model training": 4,
        },
    },

    "education": {
        "core": {
            "teach": 7,
            "teaching": 7,
            "teacher": 7,
            "tutor": 7,
            "tutoring": 7,
            "مدرب": 6,
            "تعليم": 6,
            "تعليمي": 6,
            "معلم": 6,
            "مدرس": 6,
        },
        "supporting": {
            "mentor": 3,
            "mentoring": 3,
            "training": 3,
            "course": 3,
            "courses": 3,
            "curriculum": 3,
            "lesson": 2,
            "lessons": 2,
            "student": 2,
            "students": 2,
        },
    },
    "marketing": {
        # Negative-core placement (not HARD_REJECT): these phrases occur
        # inside genuine build scopes; pure-marketing gigs still reject.
        "core": {
            "translation": 8,
            "google ads": 8,
            "facebook ads": 8,
            "digital marketing": 8,
            "lead generation": 8,
            "lead gen": 7,
            "lead generating": 7,
            "lead generator": 7,
            "lead generators": 7,
            "generación de leads": 7,
            "جلب العملاء": 7,
        },
        "supporting": {},
    },
}


# Hard rejects: unrelated work rejected when no positive signal exists.
HARD_REJECT_KEYWORDS = {
    "graphic design",
    "photoshop",
    "illustrator",
    "video editing",
    "motion graphics",
    "backlink",
    "backlinks",
    "link building",
    "copywriting",
    "commission only",
    "عمولة فقط",
    "internship",
    "intern",
    "volunteer",
    "unpaid",
    "تدريب صيفي",
    "متدرب",
    "متطوع",
    "بدون مقابل",
    # Recurring SMM-reseller storefront spam (8 corpus occurrences,
    # all rejected); hard-rejected so reposts don't burn arbitration
    # calls now that store-build collocations became positive cores.
    "خدمات smm",
    "letter writing", "request letter",
    # STL deliverables are CAD/3D-printing work, not game development.
    "stl",
    # Gambling/real-money gaming products are out of scope (policy block).
    "gambling", "casino", "igaming", "jackpot", "poker", "roulette",
    "blackjack", "satta matka", "spin and win", "spin win", "lucky jet",
    "sportsbook", "sports betting", "slot machine",
    "betting", "wager", "wagering",
    "1xbet", "dragon tiger", "dragon vs tiger",
}


# Noise: intentionally unscored terms that are too ambiguous to classify.
NOISE_KEYWORDS = {
    "system", "systems",
    "platform", "platforms",
    "api",
    "app", "apps", "application", "applications",
    "user", "users",
    "login", "signup", "session",
    "roles", "permissions",
    "نظام", "أنواع",
    "منصة", "منصات",
    "برنامج", "برامج", "برمجية",
    "موقع", "مواقع",
    "متجر", "متاجر",
    "واجهة", "تكامل", "التوثيق",
    "جوال", "موبايل",
    "المستخدمين",
    "صلاحيات",
}


# Runtime invariant: noise terms must never enter scored vocabulary.
def _all_scored_keywords():
    for polarity in (POSITIVE_KEYWORDS, NEGATIVE_KEYWORDS):
        for category in polarity.values():
            for tier in ("core", "supporting"):
                for kw in category.get(tier, {}):
                    yield kw


_collision = NOISE_KEYWORDS.intersection(_all_scored_keywords())
if _collision:
    raise AssertionError(
        "The following NOISE_KEYWORDS were found inside a scored "
        "(core/supporting) dict — this reintroduces the false-positive/"
        "false-negative bug the tiered model was designed to prevent: "
        f"{sorted(_collision)}"
    )
